//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalWebProjesi.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KurumsalWebProjesi.App_GlobalResources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string blog_adiniz_soyadiniz {
            get {
                return ResourceManager.GetString("blog_adiniz_soyadiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog İçin  Yapıla Yorumlar.
        /// </summary>
        internal static string Blog_detay_blogicinyapilanyorumlar {
            get {
                return ResourceManager.GetString("Blog_detay_blogicinyapilanyorumlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Blog_devamini_oku {
            get {
                return ResourceManager.GetString("Blog_devamini_oku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epostanız.
        /// </summary>
        internal static string blog_epostaniz {
            get {
                return ResourceManager.GetString("blog_epostaniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlığa Göre Ara.
        /// </summary>
        internal static string Blog_Filter_Basligagoreara {
            get {
                return ResourceManager.GetString("Blog_Filter_Basligagoreara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Yazılar.
        /// </summary>
        internal static string Blog_Filter_TummYazilar {
            get {
                return ResourceManager.GetString("Blog_Filter_TummYazilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Alan Yazılar.
        /// </summary>
        internal static string Blog_Filter_Yorumlu {
            get {
                return ResourceManager.GetString("Blog_Filter_Yorumlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Almayan Yazılar.
        /// </summary>
        internal static string Blog_Filter_Yorumsuz {
            get {
                return ResourceManager.GetString("Blog_Filter_Yorumsuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumunuz.
        /// </summary>
        internal static string Blog_yorumunuz {
            get {
                return ResourceManager.GetString("Blog_yorumunuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Blog_yorumyap {
            get {
                return ResourceManager.GetString("Blog_yorumyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Yorumunuz gönderildi. Kontrol edildikten sonra yayınlanacaktır..
        /// </summary>
        internal static string BlogDetay_yorumBilgilendirme {
            get {
                return ResourceManager.GetString("BlogDetay_yorumBilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum gönderilirken bir hata oluştu. Lütfen tekrar deneyin.
        /// </summary>
        internal static string BlogDetay_yorumBilgilendirmehata {
            get {
                return ResourceManager.GetString("BlogDetay_yorumBilgilendirmehata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkimizda.
        /// </summary>
        internal static string Hakkimizda_Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda_Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda Bilgiler.
        /// </summary>
        internal static string Hakkimizda_Hakkimizdabilgiler {
            get {
                return ResourceManager.GetString("Hakkimizda_Hakkimizdabilgiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimle İletişime Geç.
        /// </summary>
        internal static string home_bizimle_iletisime_gec {
            get {
                return ResourceManager.GetString("home_bizimle_iletisime_gec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetler.
        /// </summary>
        internal static string Home_footer_hizmetler {
            get {
                return ResourceManager.GetString("Home_footer_hizmetler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Blog Yazıları.
        /// </summary>
        internal static string Home_footer_sonblogyazilari {
            get {
                return ResourceManager.GetString("Home_footer-sonblogyazilari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Hakları Saklıdır.
        /// </summary>
        internal static string Home_footer_tumhaklarisaklidir {
            get {
                return ResourceManager.GetString("Home_footer_tumhaklarisaklidir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faks.
        /// </summary>
        internal static string Home_footerfaks {
            get {
                return ResourceManager.GetString("Home_footerfaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Mecralar.
        /// </summary>
        internal static string Home_footersosyalmecralar {
            get {
                return ResourceManager.GetString("Home_footersosyalmecralar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Home_footertelefon {
            get {
                return ResourceManager.GetString("Home_footertelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet Hakkında Bilgi Al.
        /// </summary>
        internal static string Home_Hizmet_Hakkinda_Bilgi_Al {
            get {
                return ResourceManager.GetString("Home_Hizmet_Hakkinda_Bilgi_Al", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Home_Hizmetlerimiz {
            get {
                return ResourceManager.GetString("Home_Hizmetlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string Home_navmenu_AnaSayfa {
            get {
                return ResourceManager.GetString("Home_navmenu_AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Home_navmenu_Blog {
            get {
                return ResourceManager.GetString("Home_navmenu_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkimizda.
        /// </summary>
        internal static string Home_navmenu_Hakkimizda {
            get {
                return ResourceManager.GetString("Home_navmenu_Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetler.
        /// </summary>
        internal static string Home_navmenu_Hizmetler {
            get {
                return ResourceManager.GetString("Home_navmenu_Hizmetler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string Home_navmenu_Iletisim {
            get {
                return ResourceManager.GetString("Home_navmenu_Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimle İletişime Geç.
        /// </summary>
        internal static string Home_slider_bizimleiletisimegec {
            get {
                return ResourceManager.GetString("Home_slider_bizimleiletisimegec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa / İletisim.
        /// </summary>
        internal static string Iletisim_anasayfa_iletisim {
            get {
                return ResourceManager.GetString("Iletisim_anasayfa_iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Iletisim_Email {
            get {
                return ResourceManager.GetString("Iletisim_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string Iletisim_isim {
            get {
                return ResourceManager.GetString("Iletisim_isim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        internal static string Iletisim_Konu {
            get {
                return ResourceManager.GetString("Iletisim_Konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        internal static string Iletisim_Mesaj {
            get {
                return ResourceManager.GetString("Iletisim_Mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Gonder.
        /// </summary>
        internal static string Iletisim_MesajGonder {
            get {
                return ResourceManager.GetString("Iletisim_MesajGonder", resourceCulture);
            }
        }
    }
}
